#!/usr/bin/env python3
"""
Production inference script for scoring candidate pairs and formatting submission TSVs.

Takes candidate pairs generated by blocking stage, extracts pairwise features,
evaluates probabilities using trained EntityMatcher, applies the calibrated
decision threshold, formats outputs according to competition rules, and verifies
them against the official validate_submission.py script.
"""

from __future__ import annotations

import argparse
import os
import subprocess
import sys
import time
from typing import Any, Dict, List, Optional, Set

import numpy as np
import pandas as pd

# Add workspace root to sys.path
WORKSPACE_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
if WORKSPACE_ROOT not in sys.path:
    sys.path.insert(0, WORKSPACE_ROOT)

from business_entity_resolution.src.features import extract_features_from_df
from business_entity_resolution.src.model import EntityMatcher
from business_entity_resolution.src.evaluation import apply_decision_rule


def score_and_export_predictions(
    s1_path: str,
    s2_path: str,
    s3_path: str,
    candidate_pairs_path: str,
    model_path: str,
    output_dir: str = "output",
    threshold: float = 0.50,
    max_matches_per_s1: Optional[int] = None,
    batch_size: int = 50_000,
    validate: bool = True,
    test_dir: Optional[str] = None,
) -> Dict[str, Any]:
    """
    Score candidates and generate final submission TSV files.
    """
    t0 = time.time()
    os.makedirs(output_dir, exist_ok=True)

    print(f"Loading trained model from: {model_path}")
    matcher = EntityMatcher.load(model_path)

    # 1. Load S1 IDs and records
    print(f"Loading Source 1 records from: {s1_path}")
    s1_df = pd.read_csv(s1_path, sep="\t", dtype=str, keep_default_na=False)
    all_s1_ids = list(s1_df["entity_id"])
    s1_dict = {
        r["entity_id"]: {
            "entity_id": r["entity_id"],
            "business_name": r.get("business_name", ""),
            "business_address": r.get("business_address", ""),
            "country": r.get("country", ""),
        }
        for _, r in s1_df.iterrows()
    }
    print(f"Loaded {len(s1_dict):,} S1 records.")

    # 2. Load candidate pairs
    print(f"Loading candidate pairs from: {candidate_pairs_path}")
    cand_file_df = pd.read_csv(candidate_pairs_path, sep="\t", dtype=str, keep_default_na=False)

    # Explode candidate list into individual pairs
    pair_rows = []
    needed_cand_ids: Set[str] = set()

    for _, row in cand_file_df.iterrows():
        s1 = row["source1_entity_id"]
        c_str = str(row["candidate_entity_ids"]).strip()
        if c_str:
            for cid in c_str.split(","):
                cid = cid.strip()
                if cid:
                    pair_rows.append((s1, cid))
                    needed_cand_ids.add(cid)

    pairs_df = pd.DataFrame(pair_rows, columns=["source1_entity_id", "candidate_entity_id"])
    print(f"Total candidate pairs to score: {len(pairs_df):,} across {len(needed_cand_ids):,} unique candidates.")

    # 3. Load Candidate Records (only needed IDs)
    cand_dict: Dict[str, Dict[str, Any]] = {}
    for src_path in [s2_path, s3_path]:
        if os.path.exists(src_path):
            print(f"Reading candidate records from: {src_path}")
            for chunk in pd.read_csv(src_path, sep="\t", dtype=str, keep_default_na=False, chunksize=250_000):
                match_chunk = chunk[chunk["entity_id"].isin(needed_cand_ids)]
                for _, r in match_chunk.iterrows():
                    cand_dict[r["entity_id"]] = {
                        "entity_id": r["entity_id"],
                        "business_name": r.get("business_name", ""),
                        "business_address": r.get("business_address", ""),
                        "country": r.get("country", ""),
                    }
                    needed_cand_ids.discard(r["entity_id"])
                if not needed_cand_ids:
                    break

    print(f"Loaded {len(cand_dict):,} candidate records.")

    # 4. Extract features in batches
    print("Extracting features with parsed record caching...")
    t_feat = time.time()
    features_df = extract_features_from_df(pairs_df, s1_dict, cand_dict)
    feat_time = time.time() - t_feat
    print(f"Extracted {len(features_df):,} feature rows in {feat_time:.2f}s ({len(features_df)/max(0.001, feat_time):.0f} pairs/sec).")

    # 5. Predict scores
    print("Running model inference...")
    t_inf = time.time()
    scores = matcher.predict_in_batches(features_df, batch_size=batch_size)
    inf_time = time.time() - t_inf
    print(f"Scored {len(scores):,} pairs in {inf_time:.3f}s ({len(scores)/max(0.001, inf_time):.0f} pairs/sec).")

    pairs_df["score"] = scores

    # 6. Apply decision rule and export matching_results.tsv
    print(f"Applying decision threshold >= {threshold:.2f}...")
    matching_df = apply_decision_rule(
        pairs_df,
        all_s1_ids=all_s1_ids,
        score_column="score",
        threshold=threshold,
        max_matches_per_s1=max_matches_per_s1,
    )

    matching_out_path = os.path.join(output_dir, "matching_results.tsv")
    matching_df.to_csv(matching_out_path, sep="\t", index=False)
    print(f"Saved matching results to: {matching_out_path} ({len(matching_df):,} S1 rows).")

    # Copy / save candidate_pairs.tsv into output folder if needed
    cand_out_path = os.path.join(output_dir, "candidate_pairs.tsv")
    if os.path.abspath(candidate_pairs_path) != os.path.abspath(cand_out_path):
        cand_file_df.to_csv(cand_out_path, sep="\t", index=False)
        print(f"Saved candidate pairs to: {cand_out_path}")

    # 7. Official submission validation check
    validator_path = os.path.join(WORKSPACE_ROOT, "student_resource", "utils", "validate_submission.py")
    if validate and os.path.exists(validator_path):
        print("\nRunning official submission validator...")
        td = test_dir or os.path.dirname(os.path.abspath(s1_path))
        cmd = [
            sys.executable,
            validator_path,
            "--matching", matching_out_path,
            "--candidate", cand_out_path,
            "--test-dir", td,
        ]
        proc = subprocess.run(cmd, capture_output=True, text=True)
        print(proc.stdout)
        if proc.returncode != 0:
            print(f"VALIDATOR WARNING/ERROR:\n{proc.stderr}")

    total_time = time.time() - t0
    return {
        "matching_results_path": matching_out_path,
        "candidate_pairs_path": cand_out_path,
        "total_pairs_scored": len(pairs_df),
        "total_s1": len(matching_df),
        "threshold_used": threshold,
        "total_runtime_seconds": round(total_time, 2),
    }


def main():
    parser = argparse.ArgumentParser(description="Score candidates and generate final submission TSVs.")
    parser.add_argument("--s1", required=True, help="Path to test_source1.tsv")
    parser.add_argument("--s2", required=True, help="Path to test_source2.tsv")
    parser.add_argument("--s3", required=True, help="Path to test_source3.tsv")
    parser.add_argument("--candidate-pairs", required=True, help="Path to candidate_pairs.tsv")
    parser.add_argument("--model", default="experiments/results/entity_matcher.pkl", help="Path to trained model")
    parser.add_argument("--output-dir", default="output", help="Directory for output TSVs")
    parser.add_argument("--threshold", type=float, default=0.50, help="Probability threshold for matching")
    parser.add_argument("--max-matches", type=int, default=None, help="Max matches allowed per S1")
    parser.add_argument("--no-validate", action="store_true", help="Skip validator script check")
    args = parser.parse_args()

    score_and_export_predictions(
        s1_path=args.s1,
        s2_path=args.s2,
        s3_path=args.s3,
        candidate_pairs_path=args.candidate_pairs,
        model_path=args.model,
        output_dir=args.output_dir,
        threshold=args.threshold,
        max_matches_per_s1=args.max_matches,
        validate=not args.no_validate,
    )


if __name__ == "__main__":
    main()
